name: Compile Assets (Mix)
on: [push, pull_request]
jobs:
  build-assets:
    strategy:
      matrix:
        operating-system:
          - ubuntu-22.04
    name: ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v1
      - name: Start NPM
        run: |
          npm install
          npx mix -p
          cat public/mix-manifest.json # See asset versions in log
