name: Format Blade Files
on: [push, pull_request]
jobs:
  format-blade-files:
    strategy:
      matrix:
        operating-system:
          - ubuntu-22.04
    name: ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Configure NPM
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Install NPM Dependencies
        run: npm install
      - name: Run Prettier
        run: ./node_modules/.bin/prettier -w *
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Blade Style Change (Prettier Blade CI)
          commit_user_name: HDVinne
          commit_user_email: hdinnovations@protonmail.com
          commit_author: HDVinnie <hdinnovations@protonmail.com>